### ISSUE TITLE
Error in Glyphs App 1108 

### ISSUE THREAD

**Issue by weiweihuanghuang** [justanotherfoundry/freemix-glyphsapp#13]
```
Traceback (most recent call last):
  File "GlyphsApp/plugins.py", line 900, in init
  File "/Users/weihuang/Library/Application Support/Glyphs/Plugins/Anchors.glyphsPalette/Contents/Resources/plugin.py", line 67, in start
    Glyphs.addCallback(self.update, UPDATEINTERFACE)
NameError: global name 'UPDATEINTERFACE' is not defined
```
@schriftgestalt ?

**Comment by schriftgestalt** [comment]
have send a pull request that fixes this.

**Comment by justanotherfoundry** [comment]
I cannot reproduce this error. Is it related to a specific beta version of Glyphs?

**Comment by schriftgestalt** [comment]
The default imports have changed in the latest cutting edge version. This improves performance quite a bit.
