### ISSUE TITLE
Anchors Palette crash in Glyphs 3 (3065)

### ISSUE THREAD

**Issue by chrisjansky** [justanotherfoundry/freemix-glyphsapp#32]
Hello,

Anchors Palette crashes latest Glyphs 3 for me when swiching masters/files. This is the error I got upon reopening Glyphs:

<img width="748" alt="Screenshot 2021-02-19 at 10 49 57" src="https://user-images.githubusercontent.com/5342612/108488202-659c2d80-72a0-11eb-9e7c-412b364025a6.png">

**Comment by schriftgestalt** [comment]
```
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/plugins.py", line 924, in init

 File "~/Library/Application Support/Glyphs 3/Repositories/freemix-glyphsapp/AnchorsPalette/Anchors.glyphsPalette/Contents/Resources/plugin.py", line 55, in settings

AttributeError: 'NoneType' object has no attribute 'frame'

App:3.4-3414 System:15.5.0 Python:3.11 Plugin:1.10-11
```
